CREATE VIEW [dbo].[MasterRawDataView] AS
SELECT g.[StateId]
      ,g.[Year]
	  ,ads.[Yes] AS 'AdoptSubsidy'
	  ,ads.[No] AS 'NoSubsidy'
      ,[Male]
      ,[Female]
	  ,r.[Native American]
      ,r.[Asian]
      ,r.[Black or African-American]
      ,r.[Native Hawaiian or Pacific Islander]
      ,r.[Hispanic]
      ,r.[White]
      ,r.[Unknown]
      ,r.[Multiracial]
	  ,pr.[NonRelative]
      ,pr.[Foster Parent]
      ,pr.[Step Parent]
      ,pr.[Other Relative]
	  ,fs.[UnMarried]
      ,fs.[Single Female]
      ,fs.[Single Male]
	  ,fa.[< 1 yr]
	  ,fa.[1 yr]
	  ,fa.[2 yr]
	  ,fa.[3 yr]
	  ,fa.[4 yr]
	  ,fa.[5 yr]
	  ,fa.[6 yr]
	  ,fa.[7 yr]
	  ,fa.[8 yr]
	  ,fa.[9 yr]
	  ,fa.[10 yr]
	  ,fa.[11 yr]
	  ,fa.[12 yr]
	  ,fa.[13 yr]
	  ,fa.[14 yr]
	  ,fa.[15 yr]
	  ,fa.[16 yr]
	  ,fa.[17 yr]
	  ,fa.[18 yr]
	  ,fa.[19 yr]
	  ,fa.[20 yr]
	  ,tpr.[< 1 mo]
      ,tpr.[1 to 5 mo]
      ,tpr.[6 to 11 mo]
      ,tpr.[12 to 17 mo]
      ,tpr.[18 to 23 mo]
      ,tpr.[24 to 29 mo]
      ,tpr.[30 to 35 mo]
      ,tpr.[3 to 4 yr]
      ,tpr.[>= 5 yr]
FROM [dbo].[GenderRawDataView] g
JOIN [dbo].[RaceRawDataView] r ON g.StateId = r.StateId AND g.[Year] = r.[Year]
JOIN [dbo].[PriorRelationshipRawDataView] pr ON pr.StateId = r.StateId AND pr.[Year] = r.[Year]
JOIN [dbo].[FamilyStructureRawDataView] fs ON fs.StateId = pr.StateId AND fs.[Year] = pr.[Year]
JOIN [dbo].[FinalAgeRawDataView] fa  ON fa.StateId = fs.StateId AND fa.[Year] = fs.[Year]
JOIN [dbo].[AdoptionSubsidyRawDataView] ads ON fa.StateId = ads.StateId AND fa.[Year] = ads.[Year]
JOIN [dbo].[TprToAdoptRawDataView] tpr ON tpr.StateId = ads.StateId AND tpr.[Year] = ads.[Year]
GO